# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%define cargo_install_lib 0

Name:           noip-duc
Version:        3.3.0
Release:        %autorelease
Summary:        No-IP Dynamic Update Client (https://www.noip.com)

SourceLicense:  Apache-2.0

# (MIT OR Apache-2.0) AND Unicode-DFS-2016
# Apache-2.0
# Apache-2.0 AND ISC AND (MIT OR Apache-2.0)
# Apache-2.0 OR ISC OR MIT
# Apache-2.0 OR MIT
# BSD-2-Clause OR Apache-2.0 OR MIT
# ISC
# MIT
# MIT OR Apache-2.0
# MIT OR Apache-2.0 OR Zlib
# MPL-2.0
# Unicode-3.0
# Unlicense OR MIT
# Zlib OR Apache-2.0 OR MIT
License:        (MIT OR Apache-2.0 AND Unicode-DFS-2016) AND Apache-2.0 AND (Apache-2.0 AND ISC AND (MIT OR Apache-2.0)) AND (Apache-2.0 OR ISC OR MIT) AND (Apache-2.0 OR MIT) AND (BSD-2-Clause OR Apache-2.0 OR MIT) AND ISC AND MIT AND (MIT OR Apache-2.0) AND (MIT OR Apache-2.0 OR Zlib) AND MPL-2.0 AND Unicode-3.0 AND (Unlicense OR MIT)
# LICENSE.dependencies contains a full license breakdown

URL:            https://www.noip.com
Source0:        https://dmej8g5cpdyqd.cloudfront.net/downloads/noip-duc_3.3.0.tar.gz

Source1:        noip-duc.conf
Source2:        noip-duc.service

Patch0:         noip-duc-3.3.0-clap-version.patch
Patch1:         noip-duc-3.3.0-hickory.patch

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  systemd-rpm-macros

Obsoletes:      noip < 2.1.20

%define _description %{expand:
No-IP Dynamic Update Client (https://www.noip.com).}

%description %{_description}

%prep
%autosetup -n noip-duc_%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%global _license_summary %{expand: %{cargo_license_summary}}
%{echo:
========= CARGO LICENSE SUMMARY ==============
%{_license_summary}
========== END LICENSE SUMMARY ===============
}

%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

install -m 600 -D %{SOURCE1} %{buildroot}%{_sysconfdir}/sysconfig/%{name}
install -m 644 -D -t %{buildroot}%{_unitdir}/ %{SOURCE2}

%if %{with check}
%check
%cargo_test
%endif

%pre
# Migrate settings from older client, if available
if [ -f /etc/no-ip2.conf ]; then
  /usr/bin/noip-duc --import >> /etc/sysconfig/noip-duc
fi

%files
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc INSTALL.md
%doc README.md
%{_bindir}/%{name}
%config(noreplace) %{_sysconfdir}/sysconfig/%{name}
%{_unitdir}/%{name}.service

%changelog
%autochangelog
